### ISSUE TITLE
Запоминать предпочтения пользователя

### ISSUE THREAD

**Issue by IlyaOvodov** [IlyaOvodov/AngelinaReader#15]
При работе с регистрацией - запоминать предпочтения пользователя, и использовать их при открытии страницы:
- язык интерфейса
- язык документа и положение галочек
- если пользователь специально указал - положение галочки "я согласен". В описании пояснить, почему по умолчанию это не делаетася.

**Comment by ongrid** [comment]
Достигается двумя вариантами. 

1. хранение предпочтений в браузерном store - самый простой вариант запоминать значения и не терять их при последующем старте вебприложения или PWA. Преимущества - простота. Минусы - как правило касаются бизнеса. (нет информации о пользователях). Также внешние сервисы могут стать оберткой вашего - ваш полностью открытый всему миру сервис могут без согласования с вами включить в какое-то приложение и, даже если предполагать альтруистический подход и бесплатные ресурсы, то вы не сможете управлять происходящим (не будете знать, что придет нагрузка, не сможете посылать пользователям уведомления). По опыту, это могут позволить себе только крупные корпорации, которые могут переварить любой highload. И опять же они во многом управляют нагрузкой через другие рычаги.

2. хранение их в модели на стороне сервера - как правило, делается в рамках внедрения авторизации и аутентификации (пользователи, роли, залогинивание, профиль). Почти все реализуют логику именно таким образом - при открытии SPA оно проверяет доступен ли профиль (REST GET /profile например, а в заголовке - Session ID). Если ответ Unauthorized - SPA показывает страницу логин:пароль. Если сессия есть, сервер отвечает 200 OK и в том же ответе возвращает словать настроек. SPA использует эти значения во views при отображении компонентов (состояния галочек и т.д.).

Второй вариант - де-факто стандарт веб-прилжений, исключает "вампиризм", описанный в п.1. Успешных кейсов по п.1 сходу не назову. Особенно в вашем случае, где используется очень дорогостоящий ресурс для обработки запросов. Скорее всего, вам уже с первых дней прода придется внедрять лимиты, тротлинг, разные ограничения (не более 1 фото в единицу времени, например).
