### ISSUE TITLE
Мультиязычный UI

### ISSUE THREAD

**Issue by IlyaOvodov** [IlyaOvodov/AngelinaReader#3]
Как минимум нужен интерфейс на EN с возможностью добавления других языков. Выбор языка в UI.

Дополнительно - выбор языка распознаваемого текста по умолчанию в зависимости от выбранного языка UI.

**Comment by ongrid** [comment]
Этот вопрос необходимо рассмотреть в контексте выбора SPA/PWA фреймворка. Большинство популярных имеет i18n библиотеки.
