### ISSUE TITLE
Греческий алфавит

### ISSUE THREAD

**Issue by Menelion** [IlyaOvodov/AngelinaReader#45]
Илья, я так понял, вам удобнее по-русски. Если скажете, что нужно репортовать по-английски, не вопрос, переведу :).

Суть в следующем: существует три формы греческого Брайля — немного об этом на моей [страничке про греческий Брайль](https://other.oire.org/Braille/Greek.html).  
Есть стандарт, который используется в Греции и республике Кипр как литературный Брайль; есть международный греческий Брайль, который используется по всему миру в формулах и математических выражениях; и есть советский математический стандарт, который слабо отличается от международного стандарта.  
Так вот, на данный момент в Angelina Braille Reader используется именно советский математический стандарт (если хотите, можете посмотреть отличия по точкам на моей странице). Это неплохо само по себе, но если кому-то придёт в голову распознавать реальную греческую книжку, он столкнётся с непредсказуемыми, мягко говоря, результатами. Попытаюсь разобраться в коде и организовать пулл-реквест по этому поводу, но пока логирую здесь, чтобы если что, вы знали, в чём проблема.

**Comment by Menelion** [comment]
@zuevval Спасибо, Валерий! Да, всё примерно так и обстоит. В принципе, могу организовать пулл-реквест, как и сказал (с этикой опенсорса и принципом «можешь — пофикси, не можешь — сообщи» знаком прекрасно :)). Ну или вы сами уже.

**Comment by zuevval** [comment]
@Menelion Андрей, я сделал Pull Request, это было несложно. А нет ли у Вас примеров фотографий "нормального" греческого текста, чтобы провести тестирование?

**Comment by zuevval** [comment]
@Menelion  ещё вопрос: у Вас на сайте написано, что признак заглавной буквы - точки 4 и 6. Как я читал в русском учебнике, признак заглавной буквы для греческих символов обозначается точками 4, 5 и 6. Это тоже нужно исправить?

**Comment by Menelion** [comment]
@zuevval Вот чего нет, того нет, к сожалению.

**Comment by Menelion** [comment]
@zuevval Да, во всяком случае, так в [Википедии](https://en.wikipedia.org/wiki/Greek_Braille), плюс 456 — явный признак советского Брайля.

**Comment by zuevval** [comment]
Хорошо, понятно! Изменил и это тоже.  Также добавил диграфы. В общем, спасибо!

**Comment by IlyaOvodov** [comment]
Я правильно понимаю, что в математических формулах при общем языке - русском, надо использовать кодировку как была? А измененную - при переводе греческого текста?
